version: '3'

services:
  db:
    image: mysql:5
    container_name: mysql-container
    restart: always

    environment:
      MYSQL_USER: leonardo
      MYSQL_ROOT_PASSWORD: maracutaia

    ports:
      - 3306:3306

    volumes:
      - ./data:/var/lib/mysql